// declare types of action
export const types = {
  ADMIN_LOGIN: "MAIN/ADMIN_LOGIN",
  SET_STATUS: "MAIN/SET_STATUS",
  SET_MESSAGE: "MAIN/SET_MESSAGE",
  SET_ADMINID : "MAIN/SET_ADMINID",
  SET_IMAGE : "MAIN/SET_IMAGE",
  SET_USERNAME : "MAIN/SET_USERNAME"
};