// declare types of action
export const types = {
  SET_ORDERS: "MAIN/SET_ORDERS",
  SET_ORDERS_OF_USER: "MAIN/SET_ORDERS_OF_USER",
  SET_VIEW_ORDERS: "MAIN/SET_VIEW_ORDERS",
  UPDATE_ORDER : "MAIN/UPDATE_ORDER",
  SET_STATUS_ORDERS : "MAIN/SET_STATUS_ORDERS",
  ADD_ORDER : "MAIN/ADD_ORDER"
};