// declare types of action
export const types = {
  USER_LOGIN: "MAIN/USER_LOGIN",
  SET_STATUS: "MAIN/SET_STATUS",
  SET_MESSAGE: "MAIN/SET_MESSAGE",
  SET_NAME : "MAIN/SET_NAME",
  SET_IMAGE : "MAIN/SET_IMAGE",
  SET_EMAIL : "MAIN/SET_EMAIL",
  SET_PHONE : "MAIN/SET_PHONE",
  SET_ADDRESS : "MAIN/SET_ADDRESS",
  SET_USERID : "MAIN/SET_USERID"
};