// declare types of action
export const types = {
  SET_PRODUCTS: "MAIN/SET_PRODUCTS",
  SET_PRODUCT: "MAIN/SET_PRODUCT",
  ADD_PRODUCT: "MAIN/ADD_PRODUCT",
  UPDATE_PRODUCT : "MAIN/UPDATE_PRODUCT",
  DELETE_PRODUCT : "MAIN/DELETE_PRODUCT"
};